name: "Setup Dependencies"
description: "Setup all common dependencies and tools for the project"
inputs:
  github_token:
    description: "GitHub token"
    required: true
  npm_token:
    description: "NPM registry token"
    required: true
  disable_node:
    description: "Disable Node.js installation"
    required: false
    default: "false"
  runner:
    description: "Runner type: 'namespace' for self-hosted namespace runners, 'github' for GitHub-hosted runners"
    required: false
    default: "namespace"
  disable_foundry:
    description: "Disable Foundry installation"
    required: false
    default: "false"
  disable_helm:
    description: "Disable Helm installation"
    required: false
    default: "false"
  disable_helm_docs:
    description: "Disable Helm Docs installation"
    required: false
    default: "false"
  disable_python:
    description: "Disable Python installation"
    required: false
    default: "false"
  disable_chart_testing:
    description: "Disable chart-testing installation"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v5

    - name: Set up turbo caching (namespace)
      if: inputs.runner == 'namespace'
      uses: namespace-actions/setup-turbocache@v0

    - name: Setup caches (namespace)
      if: inputs.runner == 'namespace'
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        path: |
          ./.turbo
          ./**/.turbo
          ~/.bun/install/cache
          ~/.cache/turbo
          ~/.cache/bun
          ~/.cache/foundry
          ~/.cache/helm
          ./kit/contracts/.generated

    - name: Setup caches (github)
      if: inputs.runner == 'github'
      uses: actions/cache@v4
      with:
        path: |
          ./.turbo
          ./**/.turbo
          ~/.bun/install/cache
          ~/.cache/turbo
          ~/.cache/bun
          ~/.cache/foundry
          ~/.cache/helm
          ./kit/contracts/.generated
        key: ${{ runner.os }}-deps-${{ hashFiles('**/bun.lock', '**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .bun-version

    - name: Install Node.js
      if: inputs.disable_node == 'false'
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        registry-url: "https://registry.npmjs.org"

    - name: Install Foundry
      if: inputs.disable_foundry == 'false'
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install Helm Docs
      if: inputs.disable_helm_docs == 'false'
      shell: bash
      run: |
        brew install norwoodj/tap/helm-docs

    - name: Install Node Gyp
      shell: bash
      run: bun install -g node-gyp

    - name: Install Bun dependencies
      shell: bash
      run: |
        bun install

    - name: Install Helm
      if: inputs.disable_helm == 'false'
      uses: azure/setup-helm@v4

    - name: Set up Python
      if: inputs.disable_python == 'false'
      uses: actions/setup-python@v6
      with:
        check-latest: true

    - name: Set up chart-testing
      if: inputs.disable_chart_testing == 'false'
      uses: helm/chart-testing-action@v2.8.0
